base_frame: "panda_link0"
tool_frame: "panda_link8"
test_links:
- panda_link0
- panda_link1
- panda_link2
- panda_link3
- panda_link4
- panda_link5
- panda_link6
- panda_link7
- panda_link8
minimum_distance: 0.1
reaction_time: 0.2
